b={ 'BVTK_Node_VTKToBlenderType': [True, True],
 'VTKAdaptiveDataSetSurfaceFilterType': [True, True, True, True, True, True, True],
 'VTKAdaptiveSubdivisionFilterType': [True, True, True, True],
 'VTKAddMembershipArrayType': [True, True, True],
 'VTKAdjacencyMatrixToEdgeTableType': [True, True, True, True],
 'VTKAggregateDataSetFilterType': [True],
 'VTKAMRCutPlaneType': [True, True],
 'VTKAMREnzoParticlesReaderType': [True, True, True, True],
 'VTKAMREnzoReaderType': [True, True, True],
 'VTKAMReXParticlesReaderType': [True, True],
 'VTKAMRFlashParticlesReaderType': [True, True, True],
 'VTKAMRFlashReaderType': [True, True],
 'VTKAMRGaussianPulseSourceType': [True, True, True],
 'VTKAMRResampleFilterType': [True, True, True, True, True, True, True, True],
 'VTKAMRSliceFilterType': [True, True, True],
 'VTKAMRToMultiBlockFilterType': [],
 'VTKAngularPeriodicFilterType': [True, True, True, True, True, True, True, True],
 'VTKAnnotationLayersAlgorithmType': [],
 'VTKAnnotationLinkType': [],
 'VTKAppendArcLengthType': [],
 'VTKAppendCompositeDataLeavesType': [True],
 'VTKAppendFilterType': [True],
 'VTKAppendPointsType': [True],
 'VTKAppendPolyDataType': [True, True],
 'VTKAppendSelectionType': [True, True],
 'VTKApplyColorsType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKApplyIconsType': [True, True, True, True, True, True],
 'VTKArcPlotterType': [True, True, True, True, True, True, True, True],
 'VTKArcSourceType': [True, True, True, True, True, True, True, True, True],
 'VTKAreaContourSpectrumFilterType': [True, True, True],
 'VTKAreaLayoutType': [True, True],
 'VTKArrayCalculatorType': [True, True, True, True, True, True, True, True, True, True],
 'VTKArrayDataAlgorithmType': [],
 'VTKArrayDataReaderType': [True, True, True],
 'VTKArrayDataWriterType': [True, True, True],
 'VTKArrayNormType': [True, True, True],
 'VTKArrayReaderType': [True, True, True],
 'VTKArrayToTableType': [],
 'VTKArrayWriterType': [True, True, True],
 'VTKArrowSourceType': [True, True, True, True, True, True],
 'VTKAssignAttributeType': [],
 'VTKAssignCoordinatesType': [True, True, True],
 'VTKAttributeDataToFieldDataFilterType': [True],
 'VTKAutoCorrelativeStatisticsType': [True, True, True, True, True, True],
 'VTKAVSucdReaderType': [True, True, True],
 'VTKAxesType': [True, True, True, True],
 'VTKBandedPolyDataContourFilterType': [True, True, True, True, True, True],
 'VTKBinCellDataFilterType': [True, True, True, True, True, True, True, True],
 'VTKBiomTableReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKBivariateLinearTableThresholdType': [True, True, True, True, True],
 'VTKBlankStructuredGridType': [True, True, True, True, True],
 'VTKBlankStructuredGridWithImageType': [],
 'VTKBlockIdScalarsType': [],
 'VTKBMPReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKBMPWriterType': [True, True, True, True, True],
 'VTKBooleanOperationPolyDataFilterType': [True, True, True],
 'VTKBooleanTextureType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKBoundedPointSourceType': [True, True, True, True, True],
 'VTKBoxClipDataSetType': [True, True, True],
 'VTKBoxType': [],
 'VTKBrownianPointsType': [True, True],
 'VTKBSplineTransformType': [True, True, True, True],
 'VTKButterflySubdivisionFilterType': [True, True],
 'VTKBYUReaderType': [True, True, True, True, True, True, True, True, True],
 'VTKBYUWriterType': [True, True, True, True, True, True, True],
 'VTKCastToConcreteType': [],
 'VTKCellCentersType': [True],
 'VTKCellDataToPointDataType': [True, True, True],
 'VTKCellDerivativesType': [True, True],
 'VTKCellDistanceSelectorType': [True, True, True],
 'VTKCellQualityType': [True, True, True],
 'VTKCellSizeFilterType': [True, True, True, True, True, True, True, True, True],
 'VTKCellTypeSourceType': [True, True, True, True, True],
 'VTKCellValidatorType': [True],
 'VTKChacoGraphReaderType': [True],
 'VTKChacoReaderType': [True, True, True, True, True],
 'VTKCheckerboardSplatterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKCirclePackLayoutType': [True],
 'VTKCirclePackToPolyDataType': [True],
 'VTKCityGMLReaderType': [True, True, True],
 'VTKCleanPolyDataType': [True, True, True, True, True, True, True, True],
 'VTKClipClosedSurfaceType': [True, True, True, True, True, True, True, True, True, True],
 'VTKClipConvexPolyDataType': [],
 'VTKClipDataSetType': [True, True, False, False, False, True],
 'VTKClipHyperOctreeType': [True, True, True, True],
 'VTKClipPolyDataType': [False, True, True, False],
 'VTKClipVolumeType': [True, True, True, True, True, True],
 'VTKCMLMoleculeReaderType': [True],
 'VTKCollapseGraphType': [],
 'VTKCollapseVerticesByArrayType': [True, True, True, True, True, True],
 'VTKCollectGraphType': [True, True],
 'VTKCollectPolyDataType': [True],
 'VTKCollectTableType': [True],
 'VTKCompositeCutterType': [True, True, True, True],
 'VTKCompositeDataGeometryFilterType': [],
 'VTKCompositeDataProbeFilterType': [True, True, True, True, True, True, True, True, True],
 'VTKCompositeDataReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKCompositeDataSetAlgorithmType': [],
 'VTKCompositeDataWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKComputeHistogram2DOutliersType': [True],
 'VTKComputeQuartilesType': [],
 'VTKConeSourceType': [True, True, False, True, True, True, False],
 'VTKConeType': [True],
 'VTKConnectedPointsFilterType': [True, True, True, True, True, True, True],
 'VTKConnectivityFilterType': [True, True, True, True, True, True],
 'VTKContingencyStatisticsType': [True, True, True, True, True],
 'VTKContinuousScatterplotType': [True],
 'VTKContour3DLinearGridType': [True, True, True, True, True],
 'VTKContourFilterType': [False, False, False, False, False, False, True],
 'VTKContourGridType': [True, True, True, True, True],
 'VTKContourLoopExtractionType': [True, True, True, True, True],
 'VTKContourTriangulatorType': [True],
 'VTKConvertSelectionDomainType': [],
 'VTKConvertSelectionType': [True, True, True, True, True],
 'VTKConvexHull2DType': [True, True, True, True, True],
 'VTKCookieCutterType': [],
 'VTKCorrelativeStatisticsType': [True, True, True, True, True],
 'VTKCountFacesType': [True],
 'VTKCountVerticesType': [True],
 'VTKCPExodusIIInSituReaderType': [True, True],
 'VTKCubeSourceType': [True, True, True, True],
 'VTKCursor2DType': [True, True, True, True, True, True, True],
 'VTKCursor3DType': [True, True, True, True, True, True, True, True],
 'VTKCurvaturesType': [True, True],
 'VTKCutMaterialType': [True, True, True, True],
 'VTKCutterType': [True, False, False, True],
 'VTKCylinderSourceType': [True, True, False, True, True],
 'VTKCylinderType': [True, True, True],
 'VTKCylindricalTransformType': [True, True],
 'VTKDataObjectAlgorithmType': [],
 'VTKDataObjectGeneratorType': [True],
 'VTKDataObjectReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKDataObjectToDataSetFilterType': [True, True, True, True, True],
 'VTKDataObjectToTableType': [True],
 'VTKDataObjectWriterType': [True, True, True, True, True],
 'VTKDataReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKDataSetAlgorithmType': [],
 'VTKDataSetGradientPrecomputeType': [],
 'VTKDataSetGradientType': [True],
 'VTKDataSetReaderType': [False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False],
 'VTKDataSetRegionSurfaceFilterType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKDataSetSurfaceFilterType': [True, True, True, True, True, True, True],
 'VTKDataSetToDataObjectFilterType': [True, True, True, True, True],
 'VTKDataSetTriangleFilterType': [True],
 'VTKDataSetWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKDataWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKDecimatePolylineFilterType': [True, True],
 'VTKDecimateProType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKDeformPointSetType': [True],
 'VTKDelaunay2DType': [True, True, True, True, True],
 'VTKDelaunay3DType': [True, True, True, True, True, True, True, True],
 'VTKDelimitedTextReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKDelimitedTextWriterType': [True, True, True, True, True],
 'VTKDEMReaderType': [True, True],
 'VTKDensifyPointCloudFilterType': [True, True, True, True, True, True, True],
 'VTKDensifyPolyDataType': [True],
 'VTKDepthImageToPointCloudType': [True, True, True, True],
 'VTKDepthSortPolyDataType': [True, True, True, True, True],
 'VTKDescriptiveStatisticsType': [True, True, True, True, True, True, True, True, True],
 'VTKDiagonalMatrixSourceType': [True, True, True, True, True, True, True],
 'VTKDICOMAlgorithmType': [True, True, True, True, True, True],
 'VTKDICOMApplyPaletteType': [True, True, True, True, True, True],
 'VTKDICOMApplyRescaleType': [True, True, True, True, True, True, True],
 'VTKDICOMCTRectifierType': [True, True, True, True, True, True, True],
 'VTKDICOMImageReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKDICOMReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKDICOMToRASType': [True, True, True, True, True, True, True, True, True, True],
 'VTKDICOMWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKDijkstraGraphGeodesicPathType': [True, True, True, True, True],
 'VTKDijkstraImageGeodesicPathType': [True, True, True, True, True, True, True, True],
 'VTKDIMACSGraphReaderType': [True, True, True],
 'VTKDIMACSGraphWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKDirectedGraphAlgorithmType': [],
 'VTKDiscreteFlyingEdges2DType': [True, True, True],
 'VTKDiscreteFlyingEdges3DType': [True, True, True, True, True, True],
 'VTKDiscreteFlyingEdgesClipper2DType': [True, True, True],
 'VTKDiscreteMarchingCubesType': [True, True, True, True, True],
 'VTKDiskSourceType': [True, True, True, True],
 'VTKDistancePolyDataFilterType': [True, True, True],
 'VTKDistanceToCameraType': [True, True, True],
 'VTKDotProductSimilarityType': [True, True, True, True, True, True, True, True, True],
 'VTKDuplicatePolyDataType': [True, True],
 'VTKEarthSourceType': [True, True, True],
 'VTKEdgeCentersType': [True],
 'VTKEdgeLayoutType': [],
 'VTKEdgePointsType': [True],
 'VTKElevationFilterType': [True, True, True],
 'VTKEllipseArcSourceType': [True, True, True, True, True, True, True],
 'VTKEllipticalButtonSourceType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKEnsembleSourceType': [True],
 'VTKEnSight6BinaryReaderType': [True, True, True, True, True, True],
 'VTKEnSight6ReaderType': [True, True, True, True, True, True],
 'VTKEnSightGoldBinaryReaderType': [True, True, True, True, True, True],
 'VTKEnSightGoldReaderType': [True, True, True, True, True, True],
 'VTKEnSightMasterServerReaderType': [True, True, True, True, True, True, True],
 'VTKEnSightWriterType': [True, True, True, True, True, True, True, True],
 'VTKEuclideanClusterExtractionType': [True, True, True, True, True, True],
 'VTKEvenlySpacedStreamlines2DType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKExodusIIReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKExodusIIWriterType': [True, True, True, True, True, True, True, True, True],
 'VTKExpandSelectedGraphType': [True, True, True, True],
 'VTKExtractArraysOverTimeType': [True],
 'VTKExtractArrayType': [True],
 'VTKExtractBlockType': [True, True],
 'VTKExtractCellsType': [],
 'VTKExtractCTHPartType': [True, True, True, True, True],
 'VTKExtractDataArraysOverTimeType': [True, True, True],
 'VTKExtractDataOverTimeType': [True],
 'VTKExtractDataSetsType': [],
 'VTKExtractEdgesType': [],
 'VTKExtractEnclosedPointsType': [True, True, True, True],
 'VTKExtractFunctionalBagPlotType': [],
 'VTKExtractGeometryType': [True, True, True],
 'VTKExtractGridType': [False, False, True],
 'VTKExtractHierarchicalBinsType': [True, True, True, True],
 'VTKExtractHistogram2DType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKExtractLevelType': [],
 'VTKExtractPieceType': [],
 'VTKExtractPointCloudPieceType': [True],
 'VTKExtractPointsType': [True, True, True],
 'VTKExtractPolyDataGeometryType': [True, True, True],
 'VTKExtractPolyDataPieceType': [True],
 'VTKExtractRectilinearGridType': [True, True, True],
 'VTKExtractSelectedArraysOverTimeType': [True],
 'VTKExtractSelectedBlockType': [True],
 'VTKExtractSelectedFrustumType': [True, True, True, True, True],
 'VTKExtractSelectedGraphType': [True],
 'VTKExtractSelectedIdsType': [True],
 'VTKExtractSelectedLocationsType': [True],
 'VTKExtractSelectedPolyDataIdsType': [],
 'VTKExtractSelectedRowsType': [True],
 'VTKExtractSelectedThresholdsType': [True],
 'VTKExtractSelectedTreeType': [],
 'VTKExtractSelectionLegacyType': [True, True, True],
 'VTKExtractSelectionType': [True, True, True],
 'VTKExtractSurfaceType': [False, True, False, False],
 'VTKExtractTemporalFieldDataType': [True],
 'VTKExtractTensorComponentsType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKExtractTimeStepsType': [True, True, True, True],
 'VTKExtractUnstructuredGridPieceType': [True],
 'VTKExtractUnstructuredGridType': [True, True, True, True, True, True, True, True, True],
 'VTKExtractUserDefinedPieceType': [True],
 'VTKExtractVectorComponentsType': [True],
 'VTKExtractVOIType': [False, False, True],
 'VTKFacetReaderType': [True],
 'VTKFacetWriterType': [True],
 'VTKFastSplatterType': [True, True, True, True, True],
 'VTKFeatureEdgesType': [True, True, True, True, True, True],
 'VTKFiberSurfaceType': [],
 'VTKFieldDataToAttributeDataFilterType': [True, True, True],
 'VTKFillHolesFilterType': [True],
 'VTKFitImplicitFunctionType': [True, True, True],
 'VTKFitToHeightMapFilterType': [True, True],
 'VTKFixedWidthTextReaderType': [True, True, True, True],
 'VTKFLUENTReaderType': [True, True],
 'VTKFlyingEdges2DType': [True, True, True],
 'VTKFlyingEdges3DType': [True, True, True, True, True, True],
 'VTKFlyingEdgesPlaneCutterType': [True, True, True],
 'VTKForceTimeType': [True, True],
 'VTKFrustumSourceType': [True, True],
 'VTKGAMBITReaderType': [True],
 'VTKGaussianCubeReader2Type': [True],
 'VTKGaussianCubeReaderType': [True, True, True],
 'VTKGaussianSplatterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKGeneralTransformType': [],
 'VTKGenerateIndexArrayType': [True, True, True, True],
 'VTKGenericClipType': [True, True, True, True, True],
 'VTKGenericContourFilterType': [True, True, True, True],
 'VTKGenericCutterType': [True, True],
 'VTKGenericDataObjectReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKGenericDataObjectWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKGenericDataSetTessellatorType': [True, True],
 'VTKGenericEnSightReaderType': [True, True, True, True, True, True],
 'VTKGenericGeometryFilterType': [True, True, True, True, True, True, True, True, True],
 'VTKGenericGlyph3DFilterType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKGenericOutlineFilterType': [],
 'VTKGenericProbeFilterType': [],
 'VTKGenericStreamTracerType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKGeoAdaptiveArcsType': [True, True, True],
 'VTKGeoArcsType': [True, True, True],
 'VTKGeoAssignCoordinatesType': [True, True, True, True],
 'VTKGeoGraticuleType': [True, True, True, True, True],
 'VTKGeometryFilterType': [False, False, False, False, False, False, False, False, False],
 'VTKGeoRandomGraphSourceType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKGeoSampleArcsType': [True, True, True, True],
 'VTKGeoSphereTransformType': [True, True],
 'VTKGeoTransformType': [],
 'VTKGESignaReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKGlobeSourceType': [True, True, True, True, True, True],
 'VTKGlyph2DType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKGlyph3DType': [True, False, False, True, True, False, True, False, False, True, True, True],
 'VTKGlyphSource2DType': [True, True, True, True, True, True, True, True, True, True],
 'VTKGradientFilterType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKGraphAlgorithmType': [],
 'VTKGraphAnnotationLayersFilterType': [],
 'VTKGraphHierarchicalBundleEdgesType': [True, True],
 'VTKGraphLayoutFilterType': [True, True, True, True, True],
 'VTKGraphLayoutType': [True, True],
 'VTKGraphReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKGraphToGlyphsType': [True, True, True, True],
 'VTKGraphToPointsType': [],
 'VTKGraphToPolyDataType': [True, True],
 'VTKGraphWeightEuclideanDistanceFilterType': [],
 'VTKGraphWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKGreedyTerrainDecimationType': [True, True, True, True, True, True, True],
 'VTKGridSynchronizedTemplates3DType': [True, True, True, True, True],
 'VTKGridTransformType': [True, True, True, True, True],
 'VTKGroupLeafVerticesType': [True],
 'VTKHedgeHogType': [True, True],
 'VTKHierarchicalBinningFilterType': [True, True, True, True],
 'VTKHierarchicalBoxDataSetAlgorithmType': [],
 'VTKHierarchicalDataExtractDataSetsType': [],
 'VTKHierarchicalDataExtractLevelType': [],
 'VTKHierarchicalDataLevelFilterType': [],
 'VTKHierarchicalDataSetGeometryFilterType': [],
 'VTKHighestDensityRegionsStatisticsType': [True, True, True, True, True],
 'VTKHoudiniPolyDataWriterType': [True],
 'VTKHullType': [],
 'VTKHyperOctreeContourFilterType': [True],
 'VTKHyperOctreeCutterType': [True, True, True],
 'VTKHyperOctreeDepthType': [],
 'VTKHyperOctreeDualGridContourFilterType': [True],
 'VTKHyperOctreeFractalSourceType': [True, True, True, True, True, True, True, True],
 'VTKHyperOctreeLimiterType': [True],
 'VTKHyperOctreeSampleFunctionType': [True, True, True, True, True, True, True, True, True, True],
 'VTKHyperOctreeSurfaceFilterType': [True, True],
 'VTKHyperOctreeToUniformGridFilterType': [],
 'VTKHyperStreamlineType': [True, True, True, True, True, True, True, True, True],
 'VTKHyperTreeGridAxisClipType': [True, True, True, True, True],
 'VTKHyperTreeGridAxisCutType': [True, True],
 'VTKHyperTreeGridAxisReflectionType': [True, True],
 'VTKHyperTreeGridCellCentersType': [True],
 'VTKHyperTreeGridContourType': [True],
 'VTKHyperTreeGridDepthLimiterType': [True],
 'VTKHyperTreeGridGeometryType': [],
 'VTKHyperTreeGridPlaneCutterType': [True, True],
 'VTKHyperTreeGridSourceType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKHyperTreeGridThresholdType': [True, True],
 'VTKHyperTreeGridToUnstructuredGridType': [],
 'VTKIconGlyphFilterType': [True, True, True, True, True, True, True, True],
 'VTKIdentityTransformType': [],
 'VTKIdFilterType': [True, True, True, True],
 'VTKImageAccumulateType': [True, True, True, True],
 'VTKImageAnisotropicDiffusion2DType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageAnisotropicDiffusion3DType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageAppendComponentsType': [True, True, True, True, True, True],
 'VTKImageAppendType': [True, True, True, True, True, True, True, True],
 'VTKImageBlendType': [True, True, True, True, True, True, True, True],
 'VTKImageBSplineCoefficientsType': [True, True, True, True, True, True, True, True, True, True],
 'VTKImageButterworthHighPassType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageButterworthLowPassType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageCacheFilterType': [True],
 'VTKImageCanvasSource2DType': [True, True, True, True, True],
 'VTKImageCastType': [True, True, True, True, True, True, True, True],
 'VTKImageChangeInformationType': [True, True, True, True, True, True, True, True],
 'VTKImageCheckerboardType': [True, True, True, True, True, True, True],
 'VTKImageCityBlockDistanceType': [True, True, True, True, True, True, True],
 'VTKImageClipType': [True],
 'VTKImageConnectivityFilterType': [True, True, True, True, True, True, True, True],
 'VTKImageConstantPadType': [True, True, True, True, True, True, True, True],
 'VTKImageContinuousDilate3DType': [True, True, True, True, True, True, True],
 'VTKImageContinuousErode3DType': [True, True, True, True, True, True, True],
 'VTKImageConvolveType': [True, True, True, True, True, True],
 'VTKImageCorrelationType': [True, True, True, True, True, True, True],
 'VTKImageCursor3DType': [True, True, True],
 'VTKImageDataGeometryFilterType': [True, True, True],
 'VTKImageDataLIC2DType': [True, True, True],
 'VTKImageDataStreamerType': [True],
 'VTKImageDataToPointSetType': [],
 'VTKImageDataToUniformGridType': [True],
 'VTKImageDifferenceType': [True, True, True, True, True, True, True, True, True, True],
 'VTKImageDilateErode3DType': [True, True, True, True, True, True, True, True, True],
 'VTKImageDivergenceType': [True, True, True, True, True, True],
 'VTKImageDotProductType': [True, True, True, True, True, True],
 'VTKImageEllipsoidSourceType': [True, True, True, True, True],
 'VTKImageEuclideanDistanceType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageEuclideanToPolarType': [True, True, True, True, True, True, True],
 'VTKImageExtractComponentsType': [True, True, True, True, True, True],
 'VTKImageFFTType': [True, True, True, True, True, True, True],
 'VTKImageFlipType': [True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageFourierCenterType': [True, True, True, True, True, True, True],
 'VTKImageGaussianSmoothType': [False, False, False, True, False, False, False, True, True],
 'VTKImageGaussianSourceType': [True, True, True],
 'VTKImageGradientMagnitudeType': [True, True, True, True, True, True, True, True],
 'VTKImageGradientType': [True, True, True, True, True, True, True, True],
 'VTKImageGridSourceType': [True, True, True, True, True, True, True],
 'VTKImageHistogramStatisticsType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageHistogramType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageHSIToRGBType': [True, True, True, True, True, True, True],
 'VTKImageHSVToRGBType': [True, True, True, True, True, True, True],
 'VTKImageHybridMedian2DType': [True, True, True, True, True, True],
 'VTKImageIdealHighPassType': [True, True, True, True, True, True, True, True, True, True],
 'VTKImageIdealLowPassType': [True, True, True, True, True, True, True, True, True, True],
 'VTKImageImportType': [True, True, True, True, True],
 'VTKImageIslandRemoval2DType': [True, True, True, True],
 'VTKImageLaplacianType': [True, True, True, True, True, True, True],
 'VTKImageLogarithmicScaleType': [True, True, True, True, True, True, True],
 'VTKImageLogicType': [True, True, True, True, True, True, True, True],
 'VTKImageLuminanceType': [True, True, True, True, True, True],
 'VTKImageMagnifyType': [True, True, True, True, True, True, True, True],
 'VTKImageMagnitudeType': [True, True, True, True, True, True],
 'VTKImageMandelbrotSourceType': [True, True, True, True, True, True, True],
 'VTKImageMapToColorsType': [False, False, False, False, False, False, False, False, False, False],
 'VTKImageMapToRGBAType': [True, True, True, True, True, True, True, True, True, True],
 'VTKImageMapToWindowLevelColorsType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageMarchingCubesType': [True, True, True, True, True],
 'VTKImageMaskBitsType': [True, True, True, True, True, True, True, True],
 'VTKImageMaskType': [True, True, True, True, True, True, True, True],
 'VTKImageMathematicsType': [True, True, True, True, True, True, True, True, True, True],
 'VTKImageMedian3DType': [True, True, True, True, True, True, True],
 'VTKImageMirrorPadType': [True, True, True, True, True, True, True],
 'VTKImageNoiseSourceType': [True, True],
 'VTKImageNonMaximumSuppressionType': [True, True, True, True, True, True, True, True],
 'VTKImageNormalizeType': [True, True, True, True, True, True],
 'VTKImageOpenClose3DType': [True, True],
 'VTKImagePadFilterType': [True, True, True, True, True, True, True],
 'VTKImagePermuteType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageQuantizeRGBToIndexType': [True, True, True, True, True, True],
 'VTKImageRange3DType': [True, True, True, True, True, True, True],
 'VTKImageReader2Type': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageRectilinearWipeType': [True, True, True, True, True, True, True, True, True],
 'VTKImageResampleType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageResizeType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageResliceToColorsType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageResliceType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageRFFTType': [True, True, True, True, True, True, True],
 'VTKImageRGBToHSIType': [True, True, True, True, True, True, True],
 'VTKImageRGBToHSVType': [True, True, True, True, True, True, True],
 'VTKImageRGBToYIQType': [True, True, True, True, True, True, True],
 'VTKImageSeedConnectivityType': [True, True, True, True],
 'VTKImageSeparableConvolutionType': [True, True, True, True, True, True, True],
 'VTKImageShiftScaleType': [True, True, True, True, True, True, True, True, True, True],
 'VTKImageShrink3DType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageSinusoidSourceType': [True, True, True, True],
 'VTKImageSkeleton2DType': [True, True, True, True, True, True, True, True],
 'VTKImageSlabResliceType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageSlabType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageSobel2DType': [True, True, True, True, True, True],
 'VTKImageSobel3DType': [True, True, True, True, True, True],
 'VTKImageSpatialAlgorithmType': [True, True, True, True, True, True],
 'VTKImageStencilAlgorithmType': [],
 'VTKImageStencilSourceType': [True, True, True],
 'VTKImageStencilToImageType': [True, True, True],
 'VTKImageStencilType': [True, True, True, True, True, True, True, True, True],
 'VTKImageThresholdConnectivityType': [True, True, True, True, True, True, True, True, True, True],
 'VTKImageThresholdType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKImageToAMRType': [True, True, True],
 'VTKImageToImageStencilType': [True, True],
 'VTKImageToPointsType': [],
 'VTKImageToPolyDataFilterType': [True, True, True, True, True, True, True, True],
 'VTKImageToStructuredGridType': [],
 'VTKImageToStructuredPointsType': [],
 'VTKImageTranslateExtentType': [True],
 'VTKImageVariance3DType': [True, True, True, True, True, True, True],
 'VTKImageWeightedSumType': [True, True, True, True, True, True, True],
 'VTKImageWrapPadType': [True, True, True, True, True, True, True],
 'VTKImageWriterType': [True, True, True, True],
 'VTKImageYIQToRGBType': [True, True, True, True, True, True, True],
 'VTKImplicitBooleanType': [True],
 'VTKImplicitDataSetType': [True, True],
 'VTKImplicitFunctionToImageStencilType': [True, True, True, True],
 'VTKImplicitHaloType': [True, True, True],
 'VTKImplicitModellerType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKImplicitPolyDataDistanceType': [True, True, True, True],
 'VTKImplicitSelectionLoopType': [True, True],
 'VTKImplicitSumType': [True],
 'VTKImplicitTextureCoordsType': [True],
 'VTKImplicitVolumeType': [True, True],
 'VTKImplicitWindowFunctionType': [True, True],
 'VTKIntegrateAttributesType': [True],
 'VTKInterpolateDataSetAttributesType': [True],
 'VTKIntersectionPolyDataFilterType': [True, True, True, True, True, True, True],
 'VTKISIReaderType': [True, True, True],
 'VTKIterativeClosestPointTransformType': [True, True, True, True, True, True],
 'VTKIVWriterType': [True],
 'VTKJavaScriptDataWriterType': [True, True, True],
 'VTKJPEGReaderType': [False, False, True, False, False, False, False, False, False, False, False, False, False, False, False],
 'VTKJPEGWriterType': [False, False, True, False, False, False, False],
 'VTKJSONImageWriterType': [True, True, True],
 'VTKKCoreDecompositionType': [True, True, True],
 'VTKKCoreLayoutType': [True, True, True, True, True, True, True, True],
 'VTKKdTreeSelectorType': [True, True, True, True],
 'VTKKMeansStatisticsType': [True, True, True, True, True, True, True, True, True],
 'VTKLabelHierarchyAlgorithmType': [],
 'VTKLabelPlacerType': [True, True, True, True, True, True, True, True, True],
 'VTKLabelSizeCalculatorType': [True, True],
 'VTKLagrangianParticleTrackerType': [True, True, True, True, True, True, True, True, True, True],
 'VTKLandmarkTransformType': [True],
 'VTKLassoStencilSourceType': [True, True, True, True, True],
 'VTKLevelIdScalarsType': [],
 'VTKLinearExtrusionFilterType': [True, True, True, True, True],
 'VTKLinearSelectorType': [True, True, True, True, True],
 'VTKLinearSubdivisionFilterType': [True, True],
 'VTKLinearToQuadraticCellsFilterType': [],
 'VTKLineSourceType': [True, True, True],
 'VTKLinkEdgelsType': [True, True, True],
 'VTKLoopBooleanPolyDataFilterType': [True, True, True],
 'VTKLoopSubdivisionFilterType': [True, True],
 'VTKLSDynaReaderType': [True, True, True, True, True, True, True, True],
 'VTKMapArrayValuesType': [True, True, True, True, True, True],
 'VTKMarchingContourFilterType': [True, True, True, True],
 'VTKMarchingCubesType': [False, False, False, False, True],
 'VTKMarchingSquaresType': [True],
 'VTKMaskFieldsType': [],
 'VTKMaskPointsFilterType': [True, True, True],
 'VTKMaskPointsType': [True, True, True, True, True, True, True, True],
 'VTKMaskPolyDataType': [True, True],
 'VTKMatricizeArrayType': [True],
 'VTKMatrixMathFilterType': [True],
 'VTKMatrixToHomogeneousTransformType': [],
 'VTKMatrixToLinearTransformType': [],
 'VTKMCubesReaderType': [True, True, True, True, True, True, True],
 'VTKMCubesWriterType': [True, True],
 'VTKMedicalImageReader2Type': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKMemoryLimitImageDataStreamerType': [True, True],
 'VTKMergeColumnsType': [True],
 'VTKMergeDataObjectFilterType': [True],
 'VTKMergeFieldsType': [True],
 'VTKMergeFilterType': [],
 'VTKMergeGraphsType': [True, True, True],
 'VTKMergeTablesType': [True, True, True, True],
 'VTKMeshQualityType': [True, True, True, True, True, True, True, True],
 'VTKMetaImageReaderType': [False, False, True, False, False, False, False, False, False, False, False, False, False, False, False],
 'VTKMetaImageWriterType': [True, True, True, True, True, True],
 'VTKMFIXReaderType': [True, True, True],
 'VTKMINCImageReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKMINCImageWriterType': [True, True, True, True, True, True, True, True],
 'VTKMNIObjectReaderType': [True],
 'VTKMNIObjectWriterType': [True, True],
 'VTKMNITagPointReaderType': [True],
 'VTKMNITagPointWriterType': [True, True],
 'VTKMNITransformReaderType': [True],
 'VTKMNITransformWriterType': [True, True],
 'VTKMoleculeAlgorithmType': [],
 'VTKMoleculeAppendType': [True],
 'VTKMoleculeToAtomBallFilterType': [True, True, True],
 'VTKMoleculeToBondStickFilterType': [],
 'VTKMoleculeToLinesFilterType': [],
 'VTKMPASReaderType': [True, True, True, True, True, True, True, True, True],
 'VTKMRCReaderType': [True],
 'VTKMultiBlockDataGroupFilterType': [],
 'VTKMultiBlockDataSetAlgorithmType': [],
 'VTKMultiBlockFromTimeSeriesFilterType': [],
 'VTKMultiBlockMergeFilterType': [],
 'VTKMultiBlockPLOT3DReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKMultiCorrelativeStatisticsType': [True, True, True, True, True, True],
 'VTKMultiNewickTreeReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKMultiObjectMassPropertiesType': [True],
 'VTKMultiThresholdType': [],
 'VTKNetCDFCFReaderType': [True, True, True, True, True, True],
 'VTKNetCDFPOPReaderType': [True, True],
 'VTKNetCDFReaderType': [True, True],
 'VTKNetworkHierarchyType': [True],
 'VTKNewickTreeReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKNewickTreeWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKNIFTIImageReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKNIFTIImageWriterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKNIFTIReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKNIFTIWriterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKNonOverlappingAMRAlgorithmType': [],
 'VTKNormalizeMatrixVectorsType': [True, True],
 'VTKNrrdReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKOBBDicerType': [True, True, True, True, True],
 'VTKOBJReaderType': [True],
 'VTKOBJWriterType': [True],
 'VTKOggTheoraWriterType': [True, True, True, True],
 'VTKOpenFOAMReaderType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKOpenGLImageGradientType': [True, True, True, True, True, True, True, True],
 'VTKOrderStatisticsType': [True, True, True, True, True, True, True, True],
 'VTKOutlineCornerFilterType': [True],
 'VTKOutlineCornerSourceType': [True, True, True, True],
 'VTKOutlineFilterType': [True],
 'VTKOutlineSourceType': [True, True, True],
 'VTKOverlappingAMRAlgorithmType': [],
 'VTKOverlappingAMRLevelIdScalarsType': [],
 'VTKPairwiseExtractHistogram2DType': [True, True, True, True, True, True, True],
 'VTKParallelCoordinatesHistogramRepresentationType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParallelCoordinatesRepresentationType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricBohemianDomeType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricBourType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricBoyType': [True, True, False, False, False, False, False, False, False, False, False, True, True, True, True],
 'VTKParametricCatalanMinimalType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricConicSpiralType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricCrossCapType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricDiniType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricEllipsoidType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricEnneperType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricFigure8KleinType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricFunctionSourceType': [True, True, True, True, True, True],
 'VTKParametricHennebergType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricKleinType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricKuenType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricMobiusType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricPluckerConoidType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricPseudosphereType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricRandomHillsType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricRomanType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricSplineType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricSuperEllipsoidType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricSuperToroidType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParametricTorusType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParticlePathFilterType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKParticleReaderType': [True, True, True, True, True],
 'VTKParticleTracerType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKPassArraysType': [True, True],
 'VTKPassInputTypeAlgorithmType': [],
 'VTKPassThroughFilterType': [],
 'VTKPassThroughType': [True, True],
 'VTKPCAAnalysisFilterType': [],
 'VTKPCACurvatureEstimationType': [True],
 'VTKPCANormalEstimationType': [True, True, True, True],
 'VTKPCAStatisticsType': [True, True, True, True, True, True, True, True, True, True],
 'VTKPCellDataToPointDataType': [True, True, True, True],
 'VTKPChacoReaderType': [True, True, True, True, True],
 'VTKPComputeHistogram2DOutliersType': [True],
 'VTKPDataSetReaderType': [True],
 'VTKPDataSetWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKPDBReaderType': [True, True, True],
 'VTKPerlinNoiseType': [True, True, True],
 'VTKPerspectiveTransformType': [],
 'VTKPerturbCoincidentVerticesType': [True],
 'VTKPExtractArraysOverTimeType': [True],
 'VTKPExtractDataArraysOverTimeType': [True, True, True],
 'VTKPExtractHistogram2DType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKPExtractSelectedArraysOverTimeType': [True],
 'VTKPhyloXMLTreeReaderType': [True, True, True, True],
 'VTKPhyloXMLTreeWriterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKPieceRequestFilterType': [True, True],
 'VTKPieceScalarsType': [True],
 'VTKPiecewiseFunctionAlgorithmType': [],
 'VTKPiecewiseFunctionShiftScaleType': [True, True, True, True],
 'VTKPImageWriterType': [True, True, True, True, True],
 'VTKPipelineGraphSourceType': [],
 'VTKPlaneCutterType': [True, True, True, True, True],
 'VTKPlanesIntersectionType': [],
 'VTKPlaneSourceType': [True, True, False, False, True, True, True],
 'VTKPlanesType': [],
 'VTKPlaneType': [True, True],
 'VTKPlatonicSolidSourceType': [True],
 'VTKPLinearExtrusionFilterType': [True, True, True, True, True, True],
 'VTKPlot3DMetaReaderType': [True],
 'VTKPLYReaderType': [True],
 'VTKPLYWriterType': [True, True, True, True, True, True, True, True, True, True],
 'VTKPMaskPointsType': [True, True, True, True, True, True, True, True],
 'VTKPNGReaderType': [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False],
 'VTKPNGWriterType': [True, True, True, True, True, True],
 'VTKPNMReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKPNMWriterType': [True, True, True, True],
 'VTKPointConnectivityFilterType': [],
 'VTKPointDataToCellDataType': [True, True, True],
 'VTKPointDensityFilterType': [True, True, True, True, True, True, True, True, True],
 'VTKPointInterpolator2DType': [True, True, True, True, True, True, True, True, True],
 'VTKPointInterpolatorType': [True, True, True, True, True, True, True],
 'VTKPointLoadType': [True, True, True, True, True],
 'VTKPointOccupancyFilterType': [True, True, True, True],
 'VTKPointSetAlgorithmType': [],
 'VTKPointSetToLabelHierarchyType': [True, True, True, True, True, True, True, True, True],
 'VTKPointSetToMoleculeFilterType': [True],
 'VTKPointSourceType': [True, False, False, True],
 'VTKPolyDataAlgorithmType': [],
 'VTKPolyDataConnectivityFilterType': [True, True, True, True, True, True, True],
 'VTKPolyDataNormalsType': [True, True, True, True, False, False, True, True],
 'VTKPolyDataPointSamplerType': [True, True, True, True, True],
 'VTKPolyDataReaderType': [False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False],
 'VTKPolyDataSilhouetteType': [True, True, True, True, True, True, True],
 'VTKPolyDataStreamerType': [True, True],
 'VTKPolyDataToImageStencilType': [True, True, True, True],
 'VTKPolyDataToReebGraphFilterType': [True],
 'VTKPolyDataWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKPolyLineSourceType': [True, True],
 'VTKPolyPlaneType': [],
 'VTKPOpenFOAMReaderType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKPostScriptWriterType': [True, True, True, True],
 'VTKPOutlineCornerFilterType': [True],
 'VTKPOutlineFilterType': [],
 'VTKPPairwiseExtractHistogram2DType': [True, True, True, True, True, True, True],
 'VTKPPolyDataNormalsType': [True, True, True, True, True, True, True, True, True],
 'VTKPProbeFilterType': [True, True, True, True, True, True, True, True, True],
 'VTKPProjectSphereFilterType': [True, True, True],
 'VTKPReflectionFilterType': [True, True, True, True],
 'VTKPResampleFilterType': [True, True],
 'VTKProbeFilterType': [True, True, True, True, True, True, True, True],
 'VTKProbePolyhedronType': [True, True],
 'VTKProbeSelectedLocationsType': [True],
 'VTKProcessIdScalarsType': [True],
 'VTKProcrustesAlignmentFilterType': [True],
 'VTKProgrammableAttributeDataFilterType': [],
 'VTKProgrammableDataObjectSourceType': [],
 'VTKProgrammableFilterType': [True],
 'VTKProgrammableGlyphFilterType': [True],
 'VTKProgrammableSourceType': [],
 'VTKProjectedTerrainPathType': [True, True, True, True],
 'VTKProjectedTextureType': [True, True, True, True, True, True, True],
 'VTKProjectSphereFilterType': [True, True, True],
 'VTKProStarReaderType': [True, True],
 'VTKProteinRibbonFilterType': [True, True, True, True, True],
 'VTKPruneTreeFilterType': [True, True],
 'VTKPSLACReaderType': [True, True, True, True],
 'VTKPSphereSourceType': [True, True, True, True, True, True, True, True, True],
 'VTKPTSReaderType': [True, True, True, True, True, True, True, True],
 'VTKPYoungsMaterialInterfaceType': [True, True, True, True, True, True, True, True, True],
 'VTKQuadraturePointInterpolatorType': [],
 'VTKQuadraturePointsGeneratorType': [],
 'VTKQuadratureSchemeDictionaryGeneratorType': [],
 'VTKQuadricClusteringType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKQuadricDecimationType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKQuadricType': [],
 'VTKQuadRotationalExtrusionFilterType': [True, True, True, True, True, True],
 'VTKQuantizePolyDataPointsType': [True, True, True, True, True, True, True, True, True],
 'VTKRadiusOutlierRemovalType': [True, True, True, True],
 'VTKRandomAttributeGeneratorType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKRandomGraphSourceType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKRandomHyperTreeGridSourceType': [True, True, True, True, True],
 'VTKRearrangeFieldsType': [],
 'VTKRectangularButtonSourceType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKRectilinearGridAlgorithmType': [],
 'VTKRectilinearGridClipType': [True],
 'VTKRectilinearGridGeometryFilterType': [True],
 'VTKRectilinearGridOutlineFilterType': [],
 'VTKRectilinearGridPartitionerType': [True, True, True],
 'VTKRectilinearGridReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKRectilinearGridToPointSetType': [],
 'VTKRectilinearGridToTetrahedraType': [True, True],
 'VTKRectilinearGridWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKRectilinearSynchronizedTemplatesType': [True, True, True, True, True, True],
 'VTKRecursiveDividingCubesType': [True, True, True],
 'VTKReduceTableType': [True, True, True],
 'VTKReflectionFilterType': [True, True, True, True],
 'VTKRegularPolygonSourceType': [True, True, True, True, True, True],
 'VTKRemoveDuplicatePolysType': [],
 'VTKRemoveGhostsType': [],
 'VTKRemoveHiddenDataType': [],
 'VTKRemoveIsolatedVerticesType': [],
 'VTKRenderedTreeAreaRepresentationType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKRendererSourceType': [True, True, True, True, True],
 'VTKRenderLargeImageType': [True],
 'VTKResampleToImageType': [True, True],
 'VTKResampleWithDataSetType': [True, True, True, True, True, True, True],
 'VTKResliceCursorPolyDataAlgorithmType': [True, True],
 'VTKReverseSenseType': [True, True],
 'VTKRibbonFilterType': [True, True, True, True, True, True, True, True],
 'VTKRISReaderType': [True, True, True],
 'VTKROIStencilSourceType': [True, True, True, True, True],
 'VTKRotationalExtrusionFilterType': [True, True, True, True, True],
 'VTKRotationFilterType': [True, True, True, True, True],
 'VTKRowQueryToTableType': [],
 'VTKRTAnalyticSourceType': [True, True, True, True, True, True, True, True, True, True],
 'VTKRTXMLPolyDataReaderType': [True, True, True, True],
 'VTKRuledSurfaceFilterType': [True, True, True, True, True, True, True, True],
 'VTKRungeKutta2Type': [],
 'VTKRungeKutta45Type': [],
 'VTKRungeKutta4Type': [],
 'VTKSampleFunctionType': [True, True, True, True, True, True, True],
 'VTKSampleImplicitFunctionFilterType': [True, True, True],
 'VTKScalarsToTextureFilterType': [True, True],
 'VTKScancoCTReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKSectorSourceType': [True, True, True, True, True, True, True],
 'VTKSegYReaderType': [True, True, True, True, True, True],
 'VTKSelectEnclosedPointsType': [True, True, True],
 'VTKSelectionAlgorithmType': [],
 'VTKSelectionSourceType': [True, True, True, True, True, True, True, True, True, True],
 'VTKSelectPolyDataType': [True, True, True, True, True],
 'VTKSelectVisiblePointsType': [True, True, True, True],
 'VTKShepardMethodType': [True, True, True, True, True],
 'VTKShrinkFilterType': [True],
 'VTKShrinkPolyDataType': [True],
 'VTKSignedDistanceType': [True, True, True],
 'VTKSimpleBondPerceiverType': [True, True],
 'VTKSimpleElevationFilterType': [True],
 'VTKSimpleImageFilterExampleType': [],
 'VTKSimplePointsReaderType': [True],
 'VTKSimplePointsWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKSLACParticleReaderType': [True],
 'VTKSLACReaderType': [True, True, True, True],
 'VTKSLCReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKSmoothPolyDataFilterType': [True, True, True, True, True, True, True, True, True],
 'VTKSMPContourGridManyPiecesType': [True, True, True, True, True],
 'VTKSMPContourGridType': [True, True, True, True, True, True],
 'VTKSMPTransformType': [],
 'VTKSMPWarpVectorType': [True],
 'VTKSparseArrayToTableType': [True],
 'VTKSpatialRepresentationFilterType': [True],
 'VTKSpherePuzzleArrowsType': [],
 'VTKSpherePuzzleType': [],
 'VTKSphereSourceType': [False, True, True, False, False, True, False, False, True],
 'VTKSpheresType': [],
 'VTKSphereTreeFilterType': [True, True, True, True, True, True],
 'VTKSphereType': [True, True],
 'VTKSphericalTransformType': [True, True],
 'VTKSPHInterpolatorType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKSplineFilterType': [True, True, True, True, True, True],
 'VTKSplineGraphEdgesType': [True, True],
 'VTKSplitByCellScalarFilterType': [True],
 'VTKSplitColumnComponentsType': [True, True],
 'VTKSplitFieldType': [],
 'VTKSQLDatabaseTableSourceType': [True, True, True, True],
 'VTKSQLiteToTableReaderType': [],
 'VTKStaticCleanPolyDataType': [True, True, True, True, True, True, True],
 'VTKStatisticalOutlierRemovalType': [True, True, True, True, True, True],
 'VTKSTLReaderType': [True, True, True],
 'VTKSTLWriterType': [True, True, True],
 'VTKStrahlerMetricType': [True],
 'VTKStreaklineFilterType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKStreamGraphType': [True, True, True],
 'VTKStreamingStatisticsType': [],
 'VTKStreamTracerType': [False, False, False, False, True, False, False, True, True, False, False, False, True, False],
 'VTKStringToCategoryType': [True],
 'VTKStringToNumericType': [True, True, True, True, True, True, True, True, True, True],
 'VTKStripperType': [False, False, False, False, False],
 'VTKStructuredGridAlgorithmType': [],
 'VTKStructuredGridAppendType': [],
 'VTKStructuredGridClipType': [True],
 'VTKStructuredGridGeometryFilterType': [True],
 'VTKStructuredGridGhostDataGeneratorType': [True],
 'VTKStructuredGridLIC2DType': [True, True, True],
 'VTKStructuredGridOutlineFilterType': [],
 'VTKStructuredGridPartitionerType': [True, True, True],
 'VTKStructuredGridReaderType': [False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False],
 'VTKStructuredGridWriterType': [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False],
 'VTKStructuredPointsReaderType': [False, False, False, False, False, False, False, True, False, True, False, False, False, False, False, False],
 'VTKStructuredPointsWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKSubdivideTetraType': [],
 'VTKSubPixelPositionEdgelsType': [True, True],
 'VTKSuperquadricSourceType': [False, False, True, True, True, True, True, False, False, False],
 'VTKSuperquadricType': [True, True, True, True, True, True, True],
 'VTKSurfaceReconstructionFilterType': [True, True],
 'VTKSynchronizedTemplates2DType': [True, True, True],
 'VTKSynchronizedTemplatesCutter3DType': [True, True, True, True, True, True, True],
 'VTKSynchronizeTimeFilterType': [True],
 'VTKTableAlgorithmType': [],
 'VTKTableBasedClipDataSetType': [True, True, True, True, True, True],
 'VTKTableFFTType': [],
 'VTKTableReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKTableToArrayType': [],
 'VTKTableToGraphType': [True],
 'VTKTableToPolyDataType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKTableToSparseArrayType': [True],
 'VTKTableToSQLiteWriterType': [],
 'VTKTableToStructuredGridType': [True, True, True, True, True, True],
 'VTKTableToTreeFilterType': [],
 'VTKTableWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKTecplotReaderType': [],
 'VTKTecplotTableReaderType': [True, True, True, True, True, True, True, True],
 'VTKTemporalArrayOperatorFilterType': [True, True, True, True],
 'VTKTemporalDataSetCacheType': [True],
 'VTKTemporalFractalType': [True, True, True, True, True, True, True, True, True],
 'VTKTemporalInterpolatorType': [True, True, True],
 'VTKTemporalPathLineFilterType': [True, True, True, True, True],
 'VTKTemporalShiftScaleType': [True, True, True, True, True, True],
 'VTKTemporalSnapToTimeStepType': [True],
 'VTKTemporalStatisticsType': [True, True, True, True],
 'VTKTemporalStreamTracerType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKTensorGlyphType': [True, True, True, True, True, True, True, True, True, True],
 'VTKTessellatedBoxSourceType': [True, True, True, True],
 'VTKTessellatorFilterType': [True, True, True, True],
 'VTKTextSourceType': [False, True, False, False],
 'VTKTexturedSphereSourceType': [True, True, True, True, True],
 'VTKTextureMapToCylinderType': [True, True, True, True],
 'VTKTextureMapToPlaneType': [True, True, True, True, True, True, True],
 'VTKTextureMapToSphereType': [True, True, True],
 'VTKThinPlateSplineTransformType': [True, True, True, True],
 'VTKThreadedSynchronizedTemplates3DType': [True, True, True, True, True, True, True],
 'VTKThresholdGraphType': [True, True],
 'VTKThresholdPointsType': [True, True],
 'VTKThresholdTableType': [True],
 'VTKThresholdTextureCoordsType': [True, True, True],
 'VTKThresholdType': [True, True, True, True, True, True, True],
 'VTKTIFFReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKTIFFWriterType': [True, True, True, True, True],
 'VTKTimeSourceExampleType': [True, True, True, True],
 'VTKTransferAttributesType': [True, True, True, True, True],
 'VTKTransformCoordinateSystemsType': [True, True],
 'VTKTransformFilterType': [True],
 'VTKTransformPolyDataFilterType': [],
 'VTKTransformTextureCoordsType': [True, True, True, True, True, True],
 'VTKTransformToGridType': [True, True, True, True],
 'VTKTransformType': [],
 'VTKTransmitImageDataPieceType': [True],
 'VTKTransmitPolyDataPieceType': [True],
 'VTKTransmitRectilinearGridPieceType': [True],
 'VTKTransmitStructuredDataPieceType': [True],
 'VTKTransmitStructuredGridPieceType': [True],
 'VTKTransmitUnstructuredGridPieceType': [True],
 'VTKTransposeMatrixType': [],
 'VTKTransposeTableType': [True, True, True],
 'VTKTreeAlgorithmType': [],
 'VTKTreeDifferenceFilterType': [True, True, True, True],
 'VTKTreeFieldAggregatorType': [True, True, True, True],
 'VTKTreeLevelsFilterType': [],
 'VTKTreeMapLayoutType': [True],
 'VTKTreeMapToPolyDataType': [True, True],
 'VTKTreeReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKTreeRingToPolyDataType': [True],
 'VTKTreeWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKTriangleFilterType': [True, True],
 'VTKTriangleMeshPointNormalsType': [],
 'VTKTriangularTCoordsType': [],
 'VTKTriangularTextureType': [True, True, True, True],
 'VTKTrimmedExtrusionFilterType': [True, True, True, True],
 'VTKTrivialProducerType': [],
 'VTKTubeFilterType': [True, False, False, True, False, False, True, True, False, False, True, False],
 'VTKTulipReaderType': [True],
 'VTKUGFacetReaderType': [True, True, True],
 'VTKUncertaintyTubeFilterType': [True],
 'VTKUndirectedGraphAlgorithmType': [],
 'VTKUniformGridAMRAlgorithmType': [],
 'VTKUniformGridGhostDataGeneratorType': [True],
 'VTKUniformGridPartitionerType': [True, True, True],
 'VTKUnsignedDistanceType': [True, True, True, True, True, True, True, True],
 'VTKUnstructuredGridAlgorithmType': [],
 'VTKUnstructuredGridBaseAlgorithmType': [],
 'VTKUnstructuredGridGeometryFilterType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKUnstructuredGridGhostCellsGeneratorType': [True, True, True, True, True, True],
 'VTKUnstructuredGridQuadricDecimationType': [True, True, True, True, True, True, True, True],
 'VTKUnstructuredGridReaderType': [False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False],
 'VTKUnstructuredGridWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKVASPAnimationReaderType': [True],
 'VTKVASPTessellationReaderType': [True],
 'VTKVectorDotType': [True, True],
 'VTKVectorNormType': [True, True],
 'VTKVectorTextType': [True],
 'VTKVeraOutReaderType': [True],
 'VTKVertexDegreeType': [],
 'VTKVertexGlyphFilterType': [],
 'VTKVideoSourceType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKVolume16ReaderType': [True, True, True, True, True, True, True, True, True, True],
 'VTKVolumeContourSpectrumFilterType': [True, True, True],
 'VTKVolumeOfRevolutionFilterType': [True, True, True, True],
 'VTKVolumeOutlineSourceType': [True, True, True, True, True, True],
 'VTKVolumeRayCastSpaceLeapingImageFilterType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKVoronoi2DType': [True, True, True, True, True, True],
 'VTKVoxelContoursToSurfaceFilterType': [True, True],
 'VTKVoxelGridType': [True, True, True, True],
 'VTKVoxelModellerType': [True, True, True, True, True],
 'VTKWarpLensType': [True, True, True, True, True, True, True, True, True, True, True],
 'VTKWarpScalarType': [False, False, True, False],
 'VTKWarpToType': [True, True, True],
 'VTKWarpVectorType': [True],
 'VTKWeightedTransformFilterType': [True, True, True, True, True, True],
 'VTKWindBladeReaderType': [True, True],
 'VTKWindowedSincPolyDataFilterType': [True, True, True, True, True, True, True, True, True, True],
 'VTKWindowToImageFilterType': [True, True, True, True, True, True],
 'VTKXdmf3ReaderType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXdmf3WriterType': [True, True, True, True],
 'VTKXGMLReaderType': [True],
 'VTKXMLDataObjectWriterType': [True, True, True, True, True, True, True, True, True, True],
 'VTKXMLDataSetWriterType': [True, True, True, True, True, True, True, True, True, True],
 'VTKXMLGenericDataObjectReaderType': [True, True, True, True],
 'VTKXMLHierarchicalBoxDataReaderType': [True, True, True, True, True, True],
 'VTKXMLHierarchicalBoxDataWriterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLHierarchicalDataReaderType': [True, True, True, True, True],
 'VTKXMLHyperOctreeReaderType': [True, True, True, True],
 'VTKXMLHyperOctreeWriterType': [True, True, True, True, True, True, True, True, True],
 'VTKXMLHyperTreeGridReaderType': [True, True, True, True],
 'VTKXMLHyperTreeGridWriterType': [True, True, True, True, True, True, True, True, True, True],
 'VTKXMLImageDataReaderType': [False, False, True, False, False],
 'VTKXMLImageDataWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLMultiBlockDataReaderType': [True, True, True, True, True],
 'VTKXMLMultiBlockDataWriterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLMultiGroupDataReaderType': [True, True, True, True, True],
 'VTKXMLPartitionedDataSetCollectionReaderType': [True, True, True, True, True],
 'VTKXMLPartitionedDataSetCollectionWriterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPartitionedDataSetReaderType': [True, True, True, True, True],
 'VTKXMLPartitionedDataSetWriterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPDataSetWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPHierarchicalBoxDataWriterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPImageDataReaderType': [True, True, True, True],
 'VTKXMLPImageDataWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPMultiBlockDataWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPolyDataReaderType': [True, True, True, True],
 'VTKXMLPolyDataWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPPolyDataReaderType': [True, True, True, True],
 'VTKXMLPPolyDataWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPRectilinearGridReaderType': [True, True, True, True],
 'VTKXMLPRectilinearGridWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPStructuredGridReaderType': [True, True, True, True],
 'VTKXMLPStructuredGridWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPTableReaderType': [True, True, True, True],
 'VTKXMLPTableWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPUniformGridAMRWriterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLPUnstructuredGridReaderType': [True, True, True, True],
 'VTKXMLPUnstructuredGridWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLRectilinearGridReaderType': [True, True, True, True, True],
 'VTKXMLRectilinearGridWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLStructuredGridReaderType': [True, True, True, True, True],
 'VTKXMLStructuredGridWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLTableReaderType': [True, True, True, True],
 'VTKXMLTableWriterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLTreeReaderType': [True, True, True, True, True, True, True, True, True],
 'VTKXMLUniformGridAMRReaderType': [True, True, True, True, True, True],
 'VTKXMLUniformGridAMRWriterType': [True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXMLUnstructuredGridReaderType': [False, True, False, False],
 'VTKXMLUnstructuredGridWriterType': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'VTKXYZMolReader2Type': [True],
 'VTKXYZMolReaderType': [True, True, True, True],
 'VTKYoungsMaterialInterfaceType': [True, True, True, True, True, True, True, True, True],
}
